sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t Ramarao002/react-docker -f Dockerfile.dev .

script:
  - docker run -e CI=true Ramarao002/react-docker npm run test