language: generic

sudo: required

services:
    - docker

before_install:
    - docker build -t ramchava/react-docker -f Dockerfile.dev .

script:
    - docker run -e CI=true ramchava/react-docker npm run test