sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t ramchava/react-docker -f Dockerfile.dev .

script:
  - docker run -e CI=true rchava/react-docker npm run test